### ISSUE TITLE
Create a language translator program using python/c/c++ #1

### ISSUE THREAD

**Issue by Pavithra-ks-06** [Pavithra-ks-06/Hacktoberfest_2022#19]
**Create a language translator program**
_a beginner friendly program to start with open source !!!_

rules to be followed:
1) create a pull request with the file name - Language translator
2) the code quality should be neat and clean
3) the program can be written in any one of the three languages- python, c or cpp

**Comment by raj-ravan** [comment]
pls assign this issue to me ,  i can do this

**Comment by Pavithra-ks-06** [comment]
I assign this issue to u @raj-ravan

**Comment by raj-ravan** [comment]
solved  

 language translator program

[https://github.com/Pavithra-ks-06/Hacktoberfest_2022/tree/main/language%20translator](url)

**Comment by raj-ravan** [comment]
i have solved this issue @Pavithra-ks-06

**Comment by Pavithra-ks-06** [comment]
great work !!
